### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by tlhunter** [wasedaigo/grille-xlsx#1]
* Can you stream the XLSX file from a download into 'xlsx' library without writing to disk?
  * Perhaps support both streaming and disk reading?
* The file lib/logger.js can be removed, and winston removed as a dependency
* You should go all in with ES6, e.g. write lib/grille-xlsx.js as a class, var -> const/let
* Maybe add istanbul as a devDependency and try for 100% coverage
* Maybe with validation errors return an array of objects like follows instead of Error objects, so that calling environment can choose how to display
  * `[{message, columnName, row, data}]`
  * ^ Shouldn't those objects also have the worksheet name?

**Comment by wasedaigo** [comment]
> The file lib/logger.js can be removed, and winston removed as a dependency

What should we use instead? using console.info is a good practice?

> You should go all in with ES6

Hm, I thought there are still people using ES5, especially in front end. 

> Maybe add istanbul as a devDependency and try for 100% coverage

Once the features became stable enough, I will consider adding it

> validation errors

returning an array can be useful. it requires fair amount of code change though

**Comment by tlhunter** [comment]
It looks like [no code](https://github.com/wasedaigo/grille-xlsx/search?utf8=%E2%9C%93&q=logger&type=) in this module is requiring the logger.js file.

I hadn't considered the possibility that someone would want to read an XLSX file from within a browser. After looking at the `xlsx` npm module it appears they do support browsers, so good point, might as well support it.

**Comment by wasedaigo** [comment]
You are right about logger, I am going to remove it

**Comment by wasedaigo** [comment]
removed
